Use -std=gnu++0x for harfbuzz, required for MinGW
Certain mingw versions (at least the one currently in use on
AppVeyor) might abort compilation with a peculiar "error: 'strdup'
was not declared in this scope" in hb-common.cc. This is due to
subtle differences between the "-std=c++0x" and "-std=gnu++0x"
options, so make sure we use the latter when building with MinGW.